# -*- coding: utf-8 -*-
"""Python 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yigTLc0NNLwFaORmK_OLs5IsNeMAVxS3
"""

!pip install mysql-connector

import mysql.connector as sql           # importing module

# Connecting the local mysql database
database = sql.connect(host = 'localhost', user = 'root', passwd = 'ferrari458', database = 'schooldata')

cur = database.cursor()


cur.execute("update student set Eng_mark = 80 where Roll_no = 122")     # Update the record 
cur.execute("select * from student")        # View the table

for i in cur:
    print(i)

cur.close()
database.commit()       # commit changes or save changes.