# -*- coding: utf-8 -*-
"""Python 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fAdv77Y_gCkyHvkzKSRP22_8K9D2WAdI
"""

# Take multiple numbers as input and print the sum
# 18 10 22 12 31
x = [int(i) for i in input('Enter integer values: ').split()]

sum = 0
for j in x:
  sum += j # sum = sum + j

print(sum)

