# -*- coding: utf-8 -*-
"""Python 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iw4XGm_PLOQ2K231dUnjJzqg3imyRYU
"""

#Assignment Day 3: From a dict, how can we print the Key whose value is maximum

s = 'welcome'
d = {}

for i in s:
  d[i] = d.get(i, 0) + 1
  

print(d)
max_key=max(d,key=d.get)
print(max_key)

q='LetsUpgrade'
d={}
for i in q:
  d[i] = d.get(i, 0) + 1
  

print(d)
max_key=max(d,key=d.get)
print(max_key)

q='Rithikha'
d={}
for i in q:
  d[i] = d.get(i, 0) + 1
  

print(d)
max_key=max(d,key=d.get)
print(max_key)

d={'rithikha':31,'deepshikha':12,'shobha':22}
print(d)
for i in x:
  d[i] = d.get(i, 0) + 1

max_key=max(d,key=d.get)
print('max valuse is :',max_key)