# -*- coding: utf-8 -*-
"""Python 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GTssoCMpmDQmy7cJA8cBqWgu5s5CVnpX

DAY 2 PROJECT ASSIGNMENT
"""

x=input('Enter a word:')

if (x[2]) == (x[4]):
  print("Congratulations ! You Won the Lottory.")
else :
   print("Better Luck Next Time.")

R = "Hippopotamus"
print(R)
S = input("Select Char from String : ").lower()
P = R.find(ip[0])

if R[P] == R[0] or R[P] == R[1] or R[P] == R[4] or R[P] == R[6] or R[P] == R[8]:
	print("Congratulations ! You won the Lottery.")
else:
	print('Better Luck next time.')

