# -*- coding: utf-8 -*-
"""Python 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_-TXkJWdoxhvel6mmPFmtleLPZ26A5y
"""

#Write a decorator, mod_div() that will add a feature to the above function which will make sure that numerator will be always greater than the denominator.



def mod_div(fun):
	def deno(a, b):
		if a < b :
			a, b = b, a
		return fun(a, b)
	return deno
	
@mod_div
def div(a, b):
	return  a // b
    
a, b = (int(i) for i in input("Enter two Numbers: ").split())


print(div(a, b))

#Write a decorator, mod_div() that will add a feature to the above function which will make sure that numerator will be always greater than the denominator.

def decorators(fun):
	def deno(x, y):
		if x < y :
			x, y = y, x
		return fun(x, y)
	return deno
	
@decorators
def div(x, y):
	return  x// y

x =int(input("Enter the x: "))
y =int(input("Enter the y: "))
print('')


print('The result is:', div(x, y))