# -*- coding: utf-8 -*-
"""Python1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gjgyr8XkfQWV7jIVi6BP039WIBgfowyZ
"""

a = int(input('Enter first no: '))
b = int(input('Enter the second no: '))

print('Sum:', a + b)

a = int(input('Enter first no: '))
b = int(input('Enter the second no: '))

print('Sum:', a + b)

a = int(input('Enter first no: '))
b = int(input('Enter the second no: '))

print('Sum:', a + b)

a = int(input('Enter first no: '))
b = int(input('Enter the second no: '))

print('Sum:', a + b)

